variable "project_name" {
  type        = string
  description = "Resource-name prefix and Project tag value."
}

variable "environment" {
  type        = string
  description = "Logical environment name; Environment tag value."
}

variable "db_subnet_ids" {
  type        = list(string)
  description = "Private subnet IDs across >= 2 AZs. AWS RDS API requires a DB subnet group to span at least 2 AZs even when the instance is single-AZ (multi_az = false on the instance, not the subnet group). RDS picks one AZ from the group at creation time."

  validation {
    condition     = length(var.db_subnet_ids) >= 2
    error_message = "db_subnet_ids must contain at least 2 subnet IDs across different AZs (RDS API requirement)."
  }
}

variable "db_sg_id" {
  type        = string
  description = "Security group ID for the RDS instance (db_sg from modules/security)."

  validation {
    condition     = startswith(var.db_sg_id, "sg-")
    error_message = "db_sg_id must be a valid security group ID starting with 'sg-'."
  }
}

variable "db_instance_class" {
  type        = string
  description = "RDS instance class (e.g. 'db.t4g.small')."
}

variable "db_allocated_storage_gb" {
  type        = number
  description = "Initial gp3 storage allocation for RDS (GiB)."
}

variable "db_max_allocated_storage_gb" {
  type        = number
  description = "Storage autoscaling ceiling for RDS (GiB). Must be greater than db_allocated_storage_gb."

  validation {
    condition     = var.db_max_allocated_storage_gb > var.db_allocated_storage_gb
    error_message = "db_max_allocated_storage_gb must be greater than db_allocated_storage_gb."
  }
}

variable "db_engine_version" {
  type        = string
  description = "Pinned PostgreSQL minor version (e.g. '15.7')."
}

variable "db_backup_retention_days" {
  type        = number
  description = "Automated backup retention period (days). Must be 1–35."

  validation {
    condition     = var.db_backup_retention_days >= 1 && var.db_backup_retention_days <= 35
    error_message = "db_backup_retention_days must be between 1 and 35."
  }
}

variable "db_master_username" {
  type        = string
  description = "RDS master username (e.g. 'moodle_admin'). Never 'postgres' or 'admin'."
}

variable "db_master_password" {
  type        = string
  sensitive   = true
  description = "RDS master password. Generated by modules/security (random_password.db_master) and passed in; also stored in Secrets Manager for runtime access by the EC2 instance."
}
